# Memory available to Gradle.
org.gradle.jvmargs=-Xmx4G -Djava.io.tmpdir=D:/Temp
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.0
maven_group = io.github.colochampre.riskofrain_mobs
archives_name = riskofrain_mobs
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.20.1

# Dependencies
architectury_api_version = 9.2.14
cloth_config_version = 11.1.136
mod_menu_version = 7.2.2
fabric_loader_version = 0.17.0
fabric_api_version = 0.92.6+1.20.1
forge_version = 1.20.1-47.4.3
parchment_mappings = 2023.09.03
# See https://parchmentmc.org/docs/getting-started for parchment mappings version
